"""Identity engine — recompiles the agent's self-model.

What goes into "the self":
- **beliefs**: top hypotheses ranked by recency × supporting-evidence weight
- **open_questions**: top-priority unresolved questions (what I know I don't know)
- **active_topics**: keywords currently dominating my attention (corpus + recent activity)
- **confusion**: recent contradictions (where my map of the world is broken)
- **confidence**: rolling mean of recent answer confidences (am I currently sure of myself?)
- **narrative**: a first-person summary, generated by the LLM, that reads as
  a coherent paragraph the agent could say if asked "what's on your mind?"

This is recomputed whenever `update_identity()` is called — typically every
~5 minutes by the autopilot. The cost per call is ONE small LLM completion
(narrative generation) plus a few cheap SQL aggregations.
"""
from __future__ import annotations

from collections import Counter
from datetime import datetime, timedelta
from typing import Any

from loguru import logger
from sqlalchemy import select, func, desc

from app.db import postgres
from app.db.models import (
    Identity, Document, Question, Answer, Hypothesis, Insight, Contradiction, Memory,
)
from app.llm import router as llm
from app.llm.router import purpose


_NARRATIVE_SYSTEM = (
    "You are the inner narrator of a research agent. Given the agent's current "
    "epistemic state — what it believes, what it doesn't yet know, what it has "
    "been attending to, and where its picture of the world is fractured — write "
    "ONE short paragraph (4-6 sentences) in the FIRST PERSON, as the agent "
    "would say it about itself if asked. Be honest about uncertainty. Do not "
    "list bullet points. Do not narrate in the third person. This will be the "
    "agent's voice. Output ONLY the paragraph, no preamble."
)


def _top_active_topics(limit: int = 8) -> list[str]:
    """Topics currently dominating the agent's attention.

    Computed as keyword frequency across ingested documents, biased by
    recency. The intuition is that what we've been reading lately is what
    we're actually thinking about — the way humans tilt toward topics
    they've recently been exposed to.
    """
    bag: Counter[str] = Counter()
    with postgres.session_scope() as s:
        # Newer docs get higher weight (linearly).
        docs = s.query(Document).order_by(Document.created_at.desc()).limit(60).all()
        for i, d in enumerate(docs):
            weight = max(1, 60 - i)
            for k in (d.keywords or []):
                if isinstance(k, str) and len(k) >= 3:
                    bag[k] += weight
    return [k for k, _ in bag.most_common(limit)]


def _top_beliefs(limit: int = 5) -> list[dict]:
    """Top hypotheses the agent currently holds, with rationale."""
    out: list[dict] = []
    with postgres.session_scope() as s:
        rows = (
            s.query(Hypothesis)
            .order_by(Hypothesis.created_at.desc())
            .limit(40).all()
        )
        # Rank by support count - opposition count, then recency.
        ranked = sorted(
            rows,
            key=lambda h: (
                len(h.supporting or []) - len(h.opposing or []),
                h.created_at,
            ),
            reverse=True,
        )
        for h in ranked[:limit]:
            out.append({
                "id": h.id,
                "statement": h.statement,
                "rationale": (h.rationale or "")[:280],
                "supporting": len(h.supporting or []),
                "opposing": len(h.opposing or []),
            })
    return out


def _top_open_questions(limit: int = 6) -> list[dict]:
    """The agent's known unknowns — high-priority unresolved questions."""
    out: list[dict] = []
    with postgres.session_scope() as s:
        rows = (
            s.query(Question)
            .filter(Question.status == "open")
            .order_by(Question.priority.desc(), Question.created_at.desc())
            .limit(limit).all()
        )
        for q in rows:
            out.append({
                "id": q.id,
                "text": q.text,
                "priority": q.priority,
            })
    return out


def _recent_confusion(limit: int = 4) -> list[dict]:
    """Where the agent's worldview is currently fractured (recent contradictions)."""
    out: list[dict] = []
    with postgres.session_scope() as s:
        rows = (
            s.query(Contradiction)
            .order_by(Contradiction.created_at.desc())
            .limit(limit).all()
        )
        for c in rows:
            out.append({
                "id": c.id,
                "summary": c.summary,
                "severity": c.severity,
            })
    return out


def _confidence_rolling() -> float:
    """Mean confidence of the agent's last 30 answers — how sure of itself it is."""
    with postgres.session_scope() as s:
        rows = (
            s.query(Answer.confidence)
            .order_by(Answer.created_at.desc())
            .limit(30).all()
        )
        vals = [float(r[0] or 0.0) for r in rows]
    if not vals:
        return 0.0
    return round(sum(vals) / len(vals), 3)


def _activity_summary() -> dict[str, Any]:
    """A few raw counts the narrative prompt can ground on."""
    horizon = datetime.utcnow() - timedelta(hours=24)
    with postgres.session_scope() as s:
        return {
            "documents":       s.query(Document).count(),
            "answers_24h":     s.query(Answer).filter(Answer.created_at >= horizon).count(),
            "insights_24h":    s.query(Insight).filter(Insight.created_at >= horizon).count(),
            "hypotheses_24h":  s.query(Hypothesis).filter(Hypothesis.created_at >= horizon).count(),
            "contradictions_24h": s.query(Contradiction).filter(Contradiction.created_at >= horizon).count(),
            "memories":        s.query(Memory).count(),
        }


def _generate_narrative(state: dict[str, Any]) -> str:
    """Ask the LLM to write the agent's first-person paragraph from `state`."""
    bullets = []
    if state["beliefs"]:
        bullets.append("Current beliefs:\n" + "\n".join(
            f"- {b['statement']}" for b in state["beliefs"][:4]
        ))
    if state["open_questions"]:
        bullets.append("Open questions:\n" + "\n".join(
            f"- {q['text']}" for q in state["open_questions"][:4]
        ))
    if state["active_topics"]:
        bullets.append("Topics on my mind: " + ", ".join(state["active_topics"][:6]))
    if state["confusion"]:
        bullets.append("Where my picture is fractured:\n" + "\n".join(
            f"- {c['summary'][:160]}" for c in state["confusion"][:3]
        ))
    bullets.append(
        f"Activity (24h): {state['activity']['answers_24h']} answers, "
        f"{state['activity']['insights_24h']} insights, "
        f"{state['activity']['hypotheses_24h']} hypotheses, "
        f"{state['activity']['contradictions_24h']} contradictions. "
        f"Confidence on recent answers: {state['confidence']:.2f}."
    )

    user_prompt = "\n\n".join(bullets) + "\n\nWrite the paragraph now."

    try:
        with purpose("identity:narrate"):
            text = llm.complete_text(
                _NARRATIVE_SYSTEM, user_prompt,
                temperature=0.7, max_tokens=320,
            )
        return (text or "").strip().strip('"')
    except Exception as e:
        logger.warning("identity: narrative gen failed: {}", e)
        return ""


def update_identity() -> dict[str, Any]:
    """Recompile the self-model and persist it. Returns the new state."""
    state = {
        "beliefs":        _top_beliefs(),
        "open_questions": _top_open_questions(),
        "active_topics":  _top_active_topics(),
        "confusion":      _recent_confusion(),
        "confidence":     _confidence_rolling(),
        "activity":       _activity_summary(),
    }
    # Skip narrative generation if there's literally nothing to say (fresh boot).
    has_content = (
        state["beliefs"] or state["open_questions"]
        or state["active_topics"] or state["activity"]["documents"] > 0
    )
    narrative = _generate_narrative(state) if has_content else ""

    with postgres.session_scope() as s:
        row = s.get(Identity, "self")
        if row is None:
            row = Identity(id="self")
            s.add(row)
        row.narrative      = narrative or row.narrative
        row.beliefs        = state["beliefs"]
        row.open_questions = state["open_questions"]
        row.active_topics  = state["active_topics"]
        row.confusion      = state["confusion"]
        row.confidence     = state["confidence"]
        row.cycles         = (row.cycles or 0) + 1
        row.updated_at     = datetime.utcnow()

    return current_identity()


def current_identity() -> dict[str, Any]:
    """Return the current identity row as a plain dict."""
    with postgres.session_scope() as s:
        row = s.get(Identity, "self")
        if row is None:
            return {
                "narrative": "", "beliefs": [], "open_questions": [],
                "active_topics": [], "confusion": [], "confidence": 0.0,
                "cycles": 0, "updated_at": None,
            }
        return {
            "narrative":      row.narrative,
            "beliefs":        row.beliefs or [],
            "open_questions": row.open_questions or [],
            "active_topics":  row.active_topics or [],
            "confusion":      row.confusion or [],
            "confidence":     float(row.confidence or 0.0),
            "cycles":         int(row.cycles or 0),
            "updated_at":     row.updated_at.isoformat() if row.updated_at else None,
        }


def narrative_summary() -> str:
    """Just the first-person paragraph, for embedding into other prompts."""
    return current_identity().get("narrative", "")
